### ISSUE TITLE
Bug? Blender PRMan - not rendering

### ISSUE THREAD

**Issue by rbfortuna** [gigeZ/RenderMan-for-Blender-installation-#2]
Installed Blender 2.79b + PRman Addon 2.15 + RendermanProServer2.17
Everytime I try to render anything using Renderman Engine..
There is a checkered blank screen and I get the message (copied from Interactive Rendering):

Exception ignored in: (bound method Rpass._del_of (renderman217.engine.Rpass object at 0x7f0945b77a20))
Traceback (most recent call last):
File "/usr/share/blender/2.79/scripts/addons/renderman217/engine.py", line 219, in _del_del self.ri
Attribute Error: ri
Exception ignored in: >
Traceback (most recent call last):
File "/usr/share/blender/2.79/scripts/addons/renderman217/_init_.py", line 51, in _del_if hasattr(self,"render_pass"):
ReferenceError: StructRNA of type PRManRender has been removed
Traceback (most recent call last):
File "/usr/share/blender/2.79/scripts/addons/renderman217/operators.py", line 492, in invoke engine.ipr = RPass(context.scene, interactive=True)
File "/usr/share/blender/2.79/scripts/addons/renderman217/engine.py", line 203, in _init_ init_prman()
File "/usr/share/blender/2.79/scripts/addons/renderman217/engine.py", line 203, in init_prman import prman
File "/opt/pixar/RenderManProServer217/bin/prman.py", line 102, in class Rif(prman_for_python.Rif):
NameError: name 'prman_for_python' is not defined

location: :-1

**Comment by rbfortuna** [comment]
Any help? Uninstalled and reinstalled all 3 software. Using Linux with update glibc and gcc 2.27 both above renderman's sys requirements

**Comment by rbfortuna** [comment]
Already tried using blender prman addon versions 2.14 2.15 and blender 2.28 and 2.29.. same results.
